name: Mirror

on:
  #workflow_dispatch
  schedule:
    - cron: "*/45 * * * *"   # every 45 minutes

permissions:
  contents: write

env:
  APT: sudo apt -y -qq -o=Dpkg::Use-Pty=0
  ARTI_GIT_DIR: /tmp/arti

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVKEY_TO_PUSH_MIRROR }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Mirror
        run: |
          cd /tmp/
          git clone --mirror "https://gitlab.torproject.org/tpo/core/arti.git" "$ARTI_GIT_DIR"
          
          cd "$ARTI_GIT_DIR"
          git push --mirror git@github.com:mycodedoesnotcompile2/arti_mirror
